### ISSUE TITLE
Ошибка при парсинге

### ISSUE THREAD

**Issue by dnrovs** [elizhabs/TGPars#12]
`Traceback (most recent call last):                           File "/data/data/com.termux/files/home/TGPars/pars.py", line 79, in <module>
    all_participants = client.get_participants(target_group, aggressive=True)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/data/data/com.termux/files/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/client/chats.py", line 507, in get_participants
    return await self.iter_participants(*args, **kwargs).collect()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/requestiter.py", line 113, in collect
    async for message in self:
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/client/chats.py", line 222, in _load_next_chunk
    results = await self.client(self.requests)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/client/users.py", line 80, in _call
    raise MultiError(exceptions, results, requests)
telethon.errors.common.MultiError: ([FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), None, FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), None, None, FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)')], [None, <telethon.tl.types.channels.ChannelParticipants object at 0xf19fd970>, None, None, <telethon.tl.types.channels.ChannelParticipants object at 0xf19fd700>, <telethon.tl.types.channels.ChannelParticipants object at 0xf19fd8c8>, None, None, None, None], [<telethon.tl.functions.channels.GetParticipantsRequest object at 0xf19fbe98>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0xf19fbef8>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0xf19fbf58>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0xf19fbfb8>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0xf19fd160>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0xf19fd1c0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0xf19fd2e0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0xf19fd460>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0xf19fd520>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0xf19fd580>])
Segmentation fault`
Что делать?

**Comment by mrGr69** [comment]
Hello!) help me pls
the last item where you need to write the telegram hash / id / phone number. send me an example command please

**Comment by German18266** [comment]
Привет.эти файлы должны лежать в C/Пользователи/твой профиль (В моем случае DEAD (Название моего ПК)).
потом открываешь любой файл с это сборки.
(перед этим ты должен получить api_id: / api_hash: / номер.
Я допустим открываю smsbot.py 
запускаю терминал.
первое что я пишу python setup.py -i 
потом нажимаешь Y и inter.
потом пишешь команду python setup.py -c и нажимаешь inter.
потом тебя просит написать api_id: , api_hash: , номер , код от телеграмм.
после ты будешь вставлять команду,которая тебе нужна)
У меня все работает)

**Comment by JenosSuiside** [comment]
> Привет.эти файлы должны лежать в C/Пользователи/твой профиль (В моем случае DEAD (Название моего ПК)). потом открываешь любой файл с это сборки. (перед этим ты должен получить api_id: / api_hash: / номер. Я допустим открываю smsbot.py запускаю терминал. первое что я пишу python setup.py -i потом нажимаешь Y и inter. потом пишешь команду python setup.py -c и нажимаешь inter. потом тебя просит написать api_id: , api_hash: , номер , код от телеграмм. после ты будешь вставлять команду,которая тебе нужна) У меня все работает)

Покажи пример команды парсинга, пожалуйста

**Comment by Komov1905** [comment]
При запуске pars всё работает и парсит. При запуске invite и sms bot появляется ошибка 
"Traceback (most recent call last):
  File "C:\PycharmProjects\Telegramm_ivite\invite.py", line 52, in <module>
    input_file = sys.argv[1]
IndexError: list index out of range
"
