### ISSUE TITLE
FloodWaitError

### ISSUE THREAD

**Issue by apsyhea** [elizhabs/TGPars#5]
Adding 1041958619                               Traceback (most recent call last):                File "/data/data/com.termux/files/home/TGPars/invite.py", line 114, in <module>                   client(InviteToChannelRequest(target_group_entity,[user_to_add]))                             File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/sync.py", line 39, in syncified                                        return loop.run_until_complete(coro)          File "/data/data/com.termux/files/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete                                      return future.result()                        File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/client/users.py", line 30, in __call__                                 return await self._call(self._sender, request, ordered=ordered)                               File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/telethon/client/users.py", line 50, in _call                                    raise errors.FloodWaitError(request=r, capture=diff)                                        telethon.errors.rpcerrorlist.FloodWaitError: A wait of 40744 seconds is required (caused by InviteToChannelRequest)                             [!] Unexpected Error #

**Comment by boot4root** [comment]
Try to check with another telegram account. make sure that you dont have shadow ban on your account.

its seems like shadow ban.

**Comment by Tooliehuncho** [comment]
From what I found testing, you might be invited same members from what you already scraped. Im trying to figure out how to delete those members so it does not overlap.
